[features]
seeds = false
[programs.localnet]
messaging = "29e5oeHhR5NmHVybD9njYc1HyAjRCGj4SqMsdikAHz94"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/teknas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
