[features]
seeds = false
[programs.localnet]
sharedwallet = "G433gWMP3PKJ526HA5ADKD6tvMPkJNB4yobEwMfZqLry"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/teknas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
